USE [PRESTAMOS_DB]
GO
IF OBJECT_ID (N'[dbo].[EMPLOYEES]') IS NOT NULL
	DROP TABLE [DBO].[EMPLOYEES];
GO
IF OBJECT_ID (N'[dbo].[CUSTOMERS_ACCOUNT]') IS NOT NULL
	DROP TABLE [DBO].[CUSTOMERS_ACCOUNT];
GO
IF OBJECT_ID (N'[dbo].[CUSTOMERS]') IS NOT NULL
	DROP TABLE [DBO].[CUSTOMERS];
GO
--TABLA CLIENTES
CREATE TABLE DBO.CUSTOMERS(
	ID INT IDENTITY(1,1) CONSTRAINT PK_CUSTOMERS PRIMARY KEY,
	FISCAL_IDENTITY VARCHAR(14) NOT NULL UNIQUE,
	FIRST_NAME VARCHAR(25) NOT NULL,
	LAST_NAME VARCHAR(25) NOT NULL,
	OFFICE_PHONE VARCHAR(14),
	MOBILE_PHONE VARCHAR(14),
	EMAIL VARCHAR(25) NULL,
	ADDRESS VARCHAR(50));
GO 
--TABLA DE CUENTASCLIENTES
CREATE TABLE DBO.CUSTOMERS_ACCOUNT(
	ID INT IDENTITY(1,1) CONSTRAINT PK_CUSTOMERS_ACCOUNT PRIMARY KEY,
	CUSTOMERS_ID INT CONSTRAINT FK_CUSTOMERS_CUSTOMERS_ACCOUNT FOREIGN KEY (CUSTOMERS_ID) REFERENCES CUSTOMERS(ID) NOT NULL,
	USERNAME VARCHAR(10) NOT NULL,
	HAS_PASSWORD VARCHAR(64) NOT NULL,
	STATUS BIT NULL);
GO 
--TABLA EMPLEADOS DEL NEGOCIO
CREATE TABLE DBO.EMPLOYEES(
	ID INT IDENTITY(1,1) CONSTRAINT PK_EMPLEADOS PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NULL,
	HAS_PASSWORD VARCHAR(64) NULL,
	STATUS BIT NULL);
GO
INSERT INTO DBO.EMPLOYEES(USERNAME, FIRST_NAME, LAST_NAME, HAS_PASSWORD, STATUS)VALUES('mdejesus','Miguel','De Jesus','',1);
INSERT INTO DBO.EMPLOYEES(USERNAME, FIRST_NAME, LAST_NAME, HAS_PASSWORD, STATUS)VALUES('hdejesus','Henrry','De Jesus','',1);
GO